name: CI/CD-pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --updates-snapshots verify

  cd:
    needs: ci
    runs-on: u8buntu-latest

    steps:
      - uses: action/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stock management system by store-keepers group"
          heroku_email: firalammii@gmail.com
          healthcheck: "https://.stock management system by store-keepers sgroup.heroku.app/actuator/health"